// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package user

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	UserExistReply struct {
		Exists bool `json:"exists,omitempty"`
	}

	UserExistReq struct {
		Id int64 `json:"id,omitempty"`
	}
)
