// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserExistReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserExistReq) Reset()         { *m = UserExistReq{} }
func (m *UserExistReq) String() string { return proto.CompactTextString(m) }
func (*UserExistReq) ProtoMessage()    {}
func (*UserExistReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserExistReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserExistReq.Unmarshal(m, b)
}
func (m *UserExistReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserExistReq.Marshal(b, m, deterministic)
}
func (m *UserExistReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserExistReq.Merge(m, src)
}
func (m *UserExistReq) XXX_Size() int {
	return xxx_messageInfo_UserExistReq.Size(m)
}
func (m *UserExistReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserExistReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserExistReq proto.InternalMessageInfo

func (m *UserExistReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserExistReply struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserExistReply) Reset()         { *m = UserExistReply{} }
func (m *UserExistReply) String() string { return proto.CompactTextString(m) }
func (*UserExistReply) ProtoMessage()    {}
func (*UserExistReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserExistReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserExistReply.Unmarshal(m, b)
}
func (m *UserExistReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserExistReply.Marshal(b, m, deterministic)
}
func (m *UserExistReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserExistReply.Merge(m, src)
}
func (m *UserExistReply) XXX_Size() int {
	return xxx_messageInfo_UserExistReply.Size(m)
}
func (m *UserExistReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserExistReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserExistReply proto.InternalMessageInfo

func (m *UserExistReply) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func init() {
	proto.RegisterType((*UserExistReq)(nil), "user.UserExistReq")
	proto.RegisterType((*UserExistReply)(nil), "user.UserExistReply")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xe4, 0xb8, 0x78, 0x42, 0x8b,
	0x53, 0x8b, 0x5c, 0x2b, 0x32, 0x8b, 0x4b, 0x82, 0x52, 0x0b, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x98, 0x32, 0x53, 0x94, 0x34, 0xb8, 0xf8, 0x90, 0xe4,
	0x0b, 0x72, 0x2a, 0x85, 0xc4, 0xb8, 0xd8, 0x52, 0x41, 0xbc, 0x62, 0xb0, 0x2a, 0x8e, 0x20, 0x28,
	0xcf, 0xc8, 0x9e, 0x0b, 0x6c, 0xa2, 0x90, 0x39, 0x17, 0x77, 0x66, 0x31, 0x5c, 0x8f, 0x90, 0x90,
	0x1e, 0xd8, 0x4e, 0x64, 0x4b, 0xa4, 0x44, 0x30, 0xc4, 0x0a, 0x72, 0x2a, 0x93, 0xd8, 0xc0, 0xee,
	0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x48, 0xee, 0x6c, 0xa5, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	// 判断用户是否存在
	IsUserExist(ctx context.Context, in *UserExistReq, opts ...grpc.CallOption) (*UserExistReply, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) IsUserExist(ctx context.Context, in *UserExistReq, opts ...grpc.CallOption) (*UserExistReply, error) {
	out := new(UserExistReply)
	err := c.cc.Invoke(ctx, "/user.user/isUserExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	// 判断用户是否存在
	IsUserExist(context.Context, *UserExistReq) (*UserExistReply, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) IsUserExist(ctx context.Context, req *UserExistReq) (*UserExistReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUserExist not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_IsUserExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserExistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).IsUserExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.user/IsUserExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).IsUserExist(ctx, req.(*UserExistReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.user",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "isUserExist",
			Handler:    _User_IsUserExist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
