// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./user_mock.go -package userclient -source $GOFILE

package userclient

import (
	"context"

	"book/user/rpc/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	UserExistReq   = user.UserExistReq
	UserExistReply = user.UserExistReply

	User interface {
		//  判断用户是否存在
		IsUserExist(ctx context.Context, in *UserExistReq) (*UserExistReply, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

//  判断用户是否存在
func (m *defaultUser) IsUserExist(ctx context.Context, in *UserExistReq) (*UserExistReply, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.IsUserExist(ctx, in)
}
