// Code generated by goctl. DO NOT EDIT!
// Source: borrow.proto

package borrow

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	BaseReply struct {
	}

	BorrowReq struct {
		// 书籍号
		BookNo string `json:"bookNo,omitempty"`
		// 借书人
		UserId int64 `json:"userId,omitempty"`
		// 预计还书时间: 时间戳（秒）
		ReturnPlanDate int64 `json:"returnPlanDate,omitempty"`
	}

	ReturnReq struct {
		// 书籍号
		BookNo string `json:"bookNo,omitempty"`
		// 借书人
		UserId int64 `json:"userId,omitempty"`
	}
)
