// Code generated by goctl. DO NOT EDIT!
// Source: borrow.proto

package main

import (
	"flag"
	"fmt"

	"book/borrow/rpc/internal/config"
	"book/borrow/rpc/internal/server"
	"book/borrow/rpc/internal/svc"
	borrow "book/borrow/rpc/pb"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/borrow.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	borrowSrv := server.NewBorrowServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		borrow.RegisterBorrowServer(grpcServer, borrowSrv)
	})
	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
